prefix owl: <http://www.w3.org/2002/07/owl#>
prefix obo: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT ?term
WHERE {
  {
    ?term a owl:Class .
		?term <http://purl.obolibrary.org/obo/IAO_0000115> ?definition .
  }
  FILTER(STR(?definition) = "." && isIRI(?term) && (regex(str(?term), UCASE("fbbt_")) || regex(str(?term), "http://purl.obolibrary.org/obo/FBbt_") || regex(str(?term), "http://purl.obolibrary.org/obo/fbbt_")))
}