prefix obo: <http://purl.obolibrary.org/obo/> 
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?entity ?property ?value
WHERE {
  VALUES ?property { rdfs:subClassOf }
  ?entity a owl:Class .
  ?value a owl:Class .
  ?entity ?property ?value .
  ?value ?property ?entity .
  }
