PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT DISTINCT ?entity ?property ?value WHERE {
  VALUES ?property { oboInOwl:id oboInOwl:hasOBONamespace }
  ?entity a owl:Class .
  FILTER NOT EXISTS {
     ?entity ?property ?value .
     FILTER(str(?value) != "")
  }
  FILTER NOT EXISTS { ?entity owl:deprecated true }
  FILTER (!isBlank(?entity))
  FILTER regex(str(?entity), "^http://purl.obolibrary.org/obo/FBbt_")
}
ORDER BY ?entity