pattern_name: larvalMotorNeuronBySegment
pattern_iri: http://purl.obolibrary.org/obo/fbbt/src/patterns/dosdp-patterns/larvalMotorNeuronBySegment.yaml
description: "Pattern for generating segment-specific terms for Drosophila larval motor neurons. This pattern is for leaf node (e.g. A1) types and not grouping classes, such as the A1-7 types."

contributors:
  - https://orcid.org/0000-0002-1373-1705

classes:
  neuron: FBbt:00005106
  neuromere: FBbt:00005140
  muscle: FBbt:00005074
  nerve: FBbt:00005105

relations: 
  sends_synaptic_output_to_cell: RO:0013009
  has_soma_location: RO:0002100
  part_of: BFO:0000050
  fasciculates_with: RO:0002101
  synapsed_via_type_Ib_bouton_to: RO:0002105
  synapsed_via_type_Is_bouton_to: RO:0002106
  synapsed_via_type_II_bouton_to: RO:0002107
  synapsed_via_type_III_bouton_to: RO:0002114

annotationProperties:
  database_cross_reference: oboInOwl:hasDbXref

vars:
  neuron_type: neuron
  neuromere: neuromere
  neuromere_short: owl:Thing
  Landgraf_name: owl:Thing
  Hoang_name: owl:Thing
  Doe_name: owl:Thing
  alt_segment_long: owl:Thing
  alt_segment_short: owl:Thing
  
list_vars:
  nerve: nerve
  muscle: muscle
  Ib_muscle: muscle
  Is_muscle: muscle
  II_muscle: muscle
  III_muscle: muscle

internal_vars:
  - var_name: Ib_muscles_cat
    input: Ib_muscle
    apply:
      join:
        sep: ' and a '
  - var_name: Is_muscles_cat
    input: Is_muscle
    apply:
      join:
        sep: ' and a '
  - var_name: II_muscles_cat
    input: II_muscle
    apply:
      join:
        sep: ' and a '
  - var_name: III_muscles_cat
    input: III_muscle
    apply:
      join:
        sep: ' and a '
  - var_name: nerves_cat
    input: nerve
    apply:
      join:
        sep: ' and a '

substitutions:
   - in: neuromere
     out: neuromere_short1
     match: "larval (.+) neuromere"
     sub: \1

name:
  text: "larval %s motor neuron of %s neuromere"
  vars:
     - Landgraf_name
     - neuromere_short1

def:
  annotations:
     - annotationProperty: database_cross_reference
       text: "FBC:Autogenerated"
  multi_clause:
    sep: " "
    clauses:
       - text: "Larval %s motor neuron with its soma in the %s neuromere."
         vars:
           - Landgraf_name
           - neuromere_short1
       - text: "It crosses the segment boundary and innervates musculature in the %s segment."
         vars:
           - alt_segment_long
       - text: "It forms type Ib synapses to a %s."
         vars:
           - Ib_muscles_cat
       - text: "It forms type Is synapses to a %s."
         vars:
           - Is_muscles_cat
       - text: "It forms type II synapses to a %s."
         vars:
           - II_muscles_cat
       - text: "It forms type III synapses to a %s."
         vars:
           - III_muscles_cat
       - text: "It fasciculates with the %s."
         vars:
           - nerves_cat

generated_synonyms:
   - text: "%s %s MN"
     vars:
       - neuromere_short1
       - Landgraf_name
   - text: "%s %s"
     vars:
       - neuromere_short1
       - Hoang_name
   - text: "%s %s MN"
     vars:
       - neuromere_short1
       - Doe_name
   - text: "%s %s MN"
     vars:
       - neuromere_short
       - Landgraf_name
   - text: "%s %s"
     vars:
       - neuromere_short
       - Hoang_name
   - text: "%s %s MN"
     vars:
       - neuromere_short
       - Doe_name

generated_related_synonyms:
   - text: "%s %s MN"
     vars:
       - alt_segment_short
       - Landgraf_name
   - text: "%s %s"
     vars:
       - alt_segment_short
       - Hoang_name
   - text: "%s %s MN"
     vars:
       - alt_segment_short
       - Doe_name
   - text: "%s %s MN"
     vars:
       - alt_segment_long
       - Landgraf_name
   - text: "%s %s"
     vars:
       - alt_segment_long
       - Hoang_name
   - text: "%s %s MN"
     vars:
       - alt_segment_long
       - Doe_name

logical_axioms:
   - axiom_type: equivalentTo
     text: "%s that 'has_soma_location' some %s"
     vars:
       - neuron_type
       - neuromere
   - axiom_type: subClassOf
     multi_clause:
      sep: " and "
      clauses:
        - text: "'fasciculates_with' some %s"
          vars:
            - nerve
   - axiom_type: subClassOf
     multi_clause:
      sep: " and "
      clauses:
        - text: "'sends_synaptic_output_to_cell' some %s"
          vars:
            - muscle
   - axiom_type: subClassOf
     multi_clause:
      sep: " and "
      clauses:
        - text: "synapsed_via_type_Ib_bouton_to some %s"
          vars:
            - Ib_muscle
   - axiom_type: subClassOf
     multi_clause:
      sep: " and "
      clauses:
        - text: "synapsed_via_type_Is_bouton_to some %s"
          vars:
            - Is_muscle
   - axiom_type: subClassOf
     multi_clause:
      sep: " and "
      clauses:
        - text: "synapsed_via_type_II_bouton_to some %s"
          vars:
            - II_muscle
   - axiom_type: subClassOf
     multi_clause:
      sep: " and "
      clauses:
        - text: "synapsed_via_type_III_bouton_to some %s"
          vars:
            - III_muscle